language: python
python:
    - "2.7"
    - "3.3"

install:
  - pip install . --use-mirrors
  - pip install -r dev_requirements.txt
  - pip install python-coveralls

branches:
  only:
    - master
    - test

script:
  - doit
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then doit coverage; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls; fi

notifications:
    email:
        on_success: change
        on_failure: change
